[build]
  command = "CI= npm run build"
  functions = "netlify/functions"
  publish = "public"

[functions]
  external_node_modules = ["express", "ejs", "serve-favicon"]
  node_bundler = "esbuild"
  included_files = ["views/**", "public/**"]

[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200

[[redirects]]
  from = "/css/*"
  to = "/css/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200